# Generated by Django 2.0.4 on 2018-04-09 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(max_length=10)),
                ('detalhes', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=200)),
                ('dataEHora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dataEHora')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('operador', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('funcao', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Operadores',
                'verbose_name': 'Operador',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chamado',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.Operador'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamado.Usuario'),
        ),
    ]
