# Generated by Django 2.0.4 on 2018-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duvidas', '0002_auto_20180419_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='categorias',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='categorias',
            field=models.ManyToManyField(null=True, to='duvidas.Categoria'),
        ),
    ]
